package com.payloads;

import java.util.HashMap;
import java.util.Map;

public class BookPayload {
	 public static Map<String, Object> createBook(String title, String description, int pageCount) {
	        Map<String, Object> data = new HashMap<>();
	        data.put("id", 0); // ID is auto-generated by the API
	        data.put("title", title);
	        data.put("description", description);
	        data.put("pageCount", pageCount);
	        data.put("excerpt", "Sample excerpt");
	        data.put("publishDate", "2025-04-05T00:00:00");
	        return data;
	    }

}
